-- H2 compatible schema (MySQL mode)

CREATE TABLE IF NOT EXISTS sys_user (
  id BIGINT NOT NULL AUTO_INCREMENT,
  username VARCHAR(50) NOT NULL,
  password VARCHAR(200) NOT NULL,
  nickname VARCHAR(50) DEFAULT NULL,
  email VARCHAR(100) DEFAULT NULL,
  phone VARCHAR(20) DEFAULT NULL,
  avatar VARCHAR(500) DEFAULT NULL,
  gender TINYINT DEFAULT 0,
  status TINYINT DEFAULT 1,
  last_login_time DATETIME DEFAULT NULL,
  last_login_ip VARCHAR(50) DEFAULT NULL,
  created_by VARCHAR(50) DEFAULT NULL,
  created_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_by VARCHAR(50) DEFAULT NULL,
  updated_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  deleted TINYINT DEFAULT 0,
  PRIMARY KEY (id),
  CONSTRAINT uk_username UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS sys_role (
  id BIGINT NOT NULL AUTO_INCREMENT,
  role_name VARCHAR(50) NOT NULL,
  role_key VARCHAR(50) NOT NULL,
  sort_order INT DEFAULT 0,
  status TINYINT DEFAULT 1,
  description VARCHAR(500) DEFAULT NULL,
  created_by VARCHAR(50) DEFAULT NULL,
  created_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_by VARCHAR(50) DEFAULT NULL,
  updated_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  deleted TINYINT DEFAULT 0,
  PRIMARY KEY (id),
  CONSTRAINT uk_role_name UNIQUE (role_name),
  CONSTRAINT uk_role_key UNIQUE (role_key)
);

CREATE TABLE IF NOT EXISTS sys_menu (
  id BIGINT NOT NULL AUTO_INCREMENT,
  parent_id BIGINT DEFAULT 0,
  menu_name VARCHAR(50) NOT NULL,
  menu_type TINYINT NOT NULL,
  path VARCHAR(200) DEFAULT NULL,
  component VARCHAR(200) DEFAULT NULL,
  icon VARCHAR(100) DEFAULT NULL,
  sort_order INT DEFAULT 0,
  permission VARCHAR(100) DEFAULT NULL,
  visible TINYINT DEFAULT 1,
  status TINYINT DEFAULT 1,
  created_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS sys_user_role (
  id BIGINT NOT NULL AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  role_id BIGINT NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT uk_user_role UNIQUE (user_id, role_id)
);

CREATE TABLE IF NOT EXISTS sys_role_menu (
  id BIGINT NOT NULL AUTO_INCREMENT,
  role_id BIGINT NOT NULL,
  menu_id BIGINT NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT uk_role_menu UNIQUE (role_id, menu_id)
);

CREATE TABLE IF NOT EXISTS sys_operation_log (
  id BIGINT NOT NULL AUTO_INCREMENT,
  user_id BIGINT DEFAULT NULL,
  username VARCHAR(50) DEFAULT NULL,
  module VARCHAR(50) DEFAULT NULL,
  operation VARCHAR(50) DEFAULT NULL,
  method VARCHAR(200) DEFAULT NULL,
  request_url VARCHAR(500) DEFAULT NULL,
  request_method VARCHAR(10) DEFAULT NULL,
  request_params TEXT DEFAULT NULL,
  response_code INT DEFAULT NULL,
  response_result TEXT DEFAULT NULL,
  ip VARCHAR(50) DEFAULT NULL,
  duration BIGINT DEFAULT NULL,
  status TINYINT DEFAULT 1,
  error_msg TEXT DEFAULT NULL,
  created_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS sys_login_log (
  id BIGINT NOT NULL AUTO_INCREMENT,
  username VARCHAR(50) DEFAULT NULL,
  ip VARCHAR(50) DEFAULT NULL,
  location VARCHAR(200) DEFAULT NULL,
  browser VARCHAR(200) DEFAULT NULL,
  os VARCHAR(200) DEFAULT NULL,
  status TINYINT DEFAULT 1,
  message VARCHAR(500) DEFAULT NULL,
  login_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS sys_config (
  id BIGINT NOT NULL AUTO_INCREMENT,
  config_key VARCHAR(100) NOT NULL,
  config_value VARCHAR(500) DEFAULT NULL,
  config_name VARCHAR(100) DEFAULT NULL,
  config_type TINYINT DEFAULT 1,
  description VARCHAR(500) DEFAULT NULL,
  created_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_config_key UNIQUE (config_key)
);
